erDiagram

  users {
    uuid id PK "binary UUID"
    string login
    string password
    string role
    bigint created_at "timestamp"
    bigint updated_at "timestamp"
    bigint deleted_at "timestamp"
  }

  tables {
    uuid id PK "binary UUID"
    uuid uploaded_by FK "binary UUID -> users.id"
    string file_path
    bigint created_at "timestamp"
    bigint deleted_at "timestamp"
  }

  table_columns {
    uuid id PK "binary UUID"
    uuid table_id FK "binary UUID -> tables.id"
    string name
    string type
  }

  charts {
    uuid id PK "binary UUID"
    string type
    uuid table_id FK "binary UUID -> tables.id"
    string name
    bigint created_at "timestamp"
    bigint updated_at "timestamp"
    bigint deleted_at "timestamp"
  }

  chart_metrics {
    uuid id PK "binary UUID"
    uuid chart_id FK "binary UUID -> charts.id"
    string column
    string aggregate_func
    string color
    string label
  }

  chart_filters {
    uuid id PK "binary UUID"
    uuid chart_id FK "binary UUID -> charts.id"
    string column_name
    string operator
    string value
  }

  charts_accesses {
    uuid id PK "binary UUID"
    uuid user_id FK "binary UUID -> users.id"
    uuid chart_id FK "binary UUID -> charts.id"
    bigint created_at "timestamp"
    bigint deleted_at "timestamp"
  }

  %% --- связи ---
  users ||--o{ tables : "uploaded_by"
  tables ||--o{ table_columns : "columns"
  tables ||--o{ charts : "source"
  charts ||--o{ chart_metrics : "metrics"
  charts ||--o{ chart_filters : "filters"
  users ||--o{ charts_accesses : "access"
  charts ||--o{ charts_accesses : "access"
